#!/bin/sh
set -euo pipefail

# Creates sed script to replace characters with their corresponding mapping via a given character map

# In-game char-to-glyph map:
<<'###'
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
00 4E 4C 52 5C 53 55 4A 50 51 54 56 48 57 46 4F # !"#$%&'()*+,-./#
3E 35 36 37 38 39 3A 3B 3C 3D 47 49 5A 58 59 4D #0123456789:;<=>?#
5D 1B 1C 1D 1E 1F 20 21 22 23 24 25 26 27 28 29 #@ABCDEFGHIJKLMNO#
2A 2B 2C 2D 2E 2F 30 31 32 33 34 00 4E 00 00 00 #PQRSTUVWXYZ \   #
00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F # abcdefghijklmno#
10 11 12 13 14 15 16 17 18 19 1A 00 00 00 00 00 #pqrstuvwxyz     #
61 43 5E 5F 3F 60 00 61 62 63 64 65 66 67 40 00 #Çüéâäà çêëèïîìÄ #
5E 00 00 68 41 69 6A 6B 00 42 44 00 00 00 45 00 #É  ôöòûù ÖÜ   ß #
6C 00 6E 6F 00 00 00 00 00 00 00 00 00 00 00 00 #á óú            #
00 00 00 00 00 6C 5F 60 00 00 00 00 00 00 00 00 #     ÁÂÀ        #
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 #                #
00 00 62 5E 64 00 6D 66 65 00 00 00 00 00 00 00 #  ÊËÈ ÍÎÏ       #
6E 45 68 69 00 00 00 00 00 6F 6A 6B 00 00 00 00 #ÓβÔÒ     ÚÛÙ    #
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 #                #
###

tr -d "\r" | {
  # Remove any markers
  printf 's/[\002\003]%s//g\n' '\+'
  # Add marker at the end
  printf 's/$/\002/\n'
  while read -r chr ord; do
    # Isolate each substituted character so that it is not accidentally matched by a UTF-8 sequence
    chr="$(printf "%s\n" "$chr" | sed -e 's/\([\$\.\*\/\[\\^]\)/\\\1/g')"
    printf "s %s \002\\$(printf '%03o' "$ord")\003 g\n" "$chr"
  done
  # Remove BOM
  printf 's/\357\273\277//g\n'
  # Replace all unmapped unsafe characters
  printf 's/[^-\1-%s]%s[^\003]%s/?%s/g\n' ' %\./0-9:;A-Z\[\]^_a-z{|}' '\(' '\)' '\1'
  # Remove remaining characters
  printf 's/[\r\002\003]%s//g\n' '\+'
}
