#!/bin/sh
set -euo pipefail
export LC_ALL=C

# Encodes text using CR-LF

crlf() {
  while IFS= read -r line; do
    printf "%s\r\n" "$line"
  done
  
  if [ -n "$line" ]; then
    printf "%s" "$line"
  fi
}

cat -- "$@" | crlf
